[repository]
name = "Hypr-DarkWindow"
authors = ["micha4w"]
commit_pins = [
    # v Hyprland                                  v Hypr-DarkWindow
    ["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "7eb7e04dea8cb92f22b7c2df4c78d4f29e28643d"], # v0.36.0
    ["19c90048d65a5660384d2fb865926a366696d6be", "7eb7e04dea8cb92f22b7c2df4c78d4f29e28643d"], # v0.37.0
    ["c5e28ebcfe00a510922779b2c568cfa52a317445", "7eb7e04dea8cb92f22b7c2df4c78d4f29e28643d"], # v0.37.1
    ["3875679755014997776e091ff8903acfb311dd2f", "c506360835a3049ec01b33ef0fdab13a1e20d314"], # v0.38.0
    ["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "c506360835a3049ec01b33ef0fdab13a1e20d314"], # v0.38.1
    ["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "e847f179adf4eab3517623e3d5209f531435a61a"], # v0.39.0
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "e847f179adf4eab3517623e3d5209f531435a61a"], # v0.39.1
    ["cba1ade848feac44b2eda677503900639581c3f4", "a0d1964d91e59ba9199991ddcece48a56dcb3fc9"], # v0.40.0
    ["ea2501d4556f84d3de86a4ae2f4b22a474555b9f", "d1c4337676d618db7199e4717c59807b4cafac5e"], # v0.41.0
    ["9e781040d9067c2711ec2e9f5b47b76ef70762b3", "ad5cb981f801e32b576617ec9290c282304c30d4"], # v0.41.1
    ["918d8340afd652b011b937d29d5eea0be08467f5", "ad5cb981f801e32b576617ec9290c282304c30d4"], # v0.41.2
    ["9a09eac79b85c846e3a865a9078a3f8ff65a9259", "58bb4f967c58334a1d6dbe0ab2442ac8984d2ac6"], # v0.42.0
    ["0f594732b063a90d44df8c5d402d658f27471dfe", "cf6795a382826218411c614b9c2d11c6bb78a368"], # v0.43.0
    ["0c7a7e2d569eeed9d6025f3eef4ea0690d90845d", "cf6795a382826218411c614b9c2d11c6bb78a368"], # v0.44.0
    ["4520b30d498daca8079365bdb909a8dea38e8d55", "dde4f7f14c3a51f244e3e8a197b468a424b39d14"], # v0.44.1
    ["a425fbebe4cf4238e48a42f724ef2208959d66cf", "8fae7b5698379be08ea61a2e7a3349da0b930a94"], # v0.45.0
    ["500d2a3580388afc8b620b0a3624147faa34f98b", "8fae7b5698379be08ea61a2e7a3349da0b930a94"], # v0.45.1
    ["12f9a0d0b93f691d4d9923716557154d74777b0a", "8fae7b5698379be08ea61a2e7a3349da0b930a94"], # v0.45.2
    ["788ae588979c2a1ff8a660f16e3c502ef5796755", "98ae7daf09a5c03e0595bc55e46059cc81d426d6"], # v0.46.0
    ["254fc2bc6000075f660b4b8ed818a6af544d1d64", "98ae7daf09a5c03e0595bc55e46059cc81d426d6"], # v0.46.1
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "98ae7daf09a5c03e0595bc55e46059cc81d426d6"], # v0.46.2
    ["04ac46c54357278fc68f0a95d26347ea0db99496", "ae5725442267ae7ae417ca2b27840b0f84edcf78"], # v0.47.0
    ["75dff7205f6d2bd437abfb4196f700abee92581a", "ae5725442267ae7ae417ca2b27840b0f84edcf78"], # v0.47.1
    ["882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff", "ae5725442267ae7ae417ca2b27840b0f84edcf78"], # v0.47.2
    ["5ee35f914f921e5696030698e74fb5566a804768", "2d2e7ebac5c52cb23f3cbf06052ceba47a73802d"], # v0.48.0
    ["29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc", "2d2e7ebac5c52cb23f3cbf06052ceba47a73802d"], # v0.48.1
    ["9958d297641b5c84dcff93f9039d80a5ad37ab00", "26300e4b5358899d060edfbc426bd1ecce670ae5"], # v0.49.0
    ["c4a4c341568944bd4fb9cd503558b2de602c0213", "c1cdd7146b18a9fcc8095817ef4c4711d4389464"], # v0.50.0
    ["4e242d086e20b32951fdc0ebcbfb4d41b5be8dcc", "c1cdd7146b18a9fcc8095817ef4c4711d4389464"], # v0.50.1
    ["46174f78b374b6cea669c48880877a8bdcf7802f", "c1cdd7146b18a9fcc8095817ef4c4711d4389464"], # v0.51.0
    ["71a1216abcc7031776630a6d88f105605c4dc1c9", "c1cdd7146b18a9fcc8095817ef4c4711d4389464"], # v0.51.1
]

[Hypr-DarkWindow]
description = "Apply custom shaders to any Window!"
authors = ["micha4w"]
output = "out/hypr-darkwindow.so"
build = [
    "make all -j",
]
