[Hypr-DarkWindow]
description = "Invert the colors of specific Windows"
authors = ["micha4w"]
output = "out/hypr-darkwindow.so"
build = [
    "make all",
]
commit_pins = [
    # v Hyprland                                  v Hypr-DarkWindow
    ["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "7eb7e04dea8cb92f22b7c2df4c78d4f29e28643d"], # v0.36.0
    ["19c90048d65a5660384d2fb865926a366696d6be", "7eb7e04dea8cb92f22b7c2df4c78d4f29e28643d"], # v0.37.0
    ["c5e28ebcfe00a510922779b2c568cfa52a317445", "7eb7e04dea8cb92f22b7c2df4c78d4f29e28643d"], # v0.37.1
    ["3875679755014997776e091ff8903acfb311dd2f", "c506360835a3049ec01b33ef0fdab13a1e20d314"], # v0.38.0
    ["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "c506360835a3049ec01b33ef0fdab13a1e20d314"], # v0.38.1
    ["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "e847f179adf4eab3517623e3d5209f531435a61a"], # v0.39.0
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "e847f179adf4eab3517623e3d5209f531435a61a"], # v0.39.1
    ["cba1ade848feac44b2eda677503900639581c3f4", "a0d1964d91e59ba9199991ddcece48a56dcb3fc9"], # v0.40.0
]
